services:
  postgres:
    image: postgres:16
    container_name: ssma_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - ssma_net

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: ssma_backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PYTHONPATH: /app
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq # new
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/backend/uploads
    command: >
      bash -c "
      python init_db.py &&
      python add_post.py &&
      uvicorn main:app --host 0.0.0.0 --port 8000
      "
    networks:
      - ssma_net

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL} # "http://ssma_backend:8000"
    container_name: ssma_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - ssma_net

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "5672:5672" # Messaging
      - "15672:15672" # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: bunny_pass
      RABBITMQ_DEFAULT_VHOST: /
      # RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_NODE_PORT: ${RABBITMQ_PORT}
      # RABBITMQ_QUEUE: ${RABBITMQ_QUEUE}
    restart: unless-stopped
    networks:
      - ssma_net


  image_resizer:
    build:
      context: .
      dockerfile: image_resizer/Dockerfile
    container_name: ssma_image_resizer
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE}
    depends_on:
      - rabbitmq
    volumes:
      - ./backend/uploads:/app/backend/uploads  # Read originals and save small images
    restart: unless-stopped
    networks:
      - ssma_net

volumes:
  postgres_data:

networks:
  ssma_net:
    driver: bridge