components:
  schemas:
    Body_user_create_users__post:
      properties:
        email:
          title: Email
          type: string
        name:
          title: Name
          type: string
        surname:
          title: Surname
          type: string
        username:
          title: Username
          type: string
      required:
      - username
      - name
      - surname
      - email
      title: Body_user_create_users__post
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    User:
      properties:
        email:
          title: Email
          type: string
        id:
          anyOf:
          - type: integer
          - type: 'null'
          title: Id
        name:
          title: Name
          type: string
        surname:
          title: Surname
          type: string
        username:
          title: Username
          type: string
      required:
      - username
      - name
      - surname
      - email
      title: User
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  description: This is an API for a small project called 'Simple Social Media', which
    is being developed as part of the 'Software Engineering' course.
  title: Simple Social Media API
  version: '0.1'
openapi: 3.1.0
paths:
  /users/:
    get:
      operationId: users_list_users__get
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/User'
                title: Response Users List Users  Get
                type: array
          description: Successful Response
      summary: Users List
      tags:
      - Users
    post:
      operationId: user_create_users__post
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Body_user_create_users__post'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: User Create
      tags:
      - Users
  /users/search:
    get:
      operationId: users_by_query_users_search_get
      parameters:
      - in: query
        name: query
        required: true
        schema:
          title: Query
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/User'
                title: Response Users By Query Users Search Get
                type: array
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Users By Query
      tags:
      - Users
  /users/username/{username}:
    get:
      operationId: user_by_name_users_username__username__get
      parameters:
      - in: path
        name: username
        required: true
        schema:
          title: Username
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: User By Name
      tags:
      - Users
  /users/{user_id}:
    delete:
      operationId: user_delete_by_id_users__user_id__delete
      parameters:
      - in: path
        name: user_id
        required: true
        schema:
          title: User Id
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: User Delete By Id
      tags:
      - Users
    get:
      operationId: user_by_id_users__user_id__get
      parameters:
      - in: path
        name: user_id
        required: true
        schema:
          title: User Id
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: User By Id
      tags:
      - Users
