# Git Hub Container Registry Deployment
# wird nur dann benÃ¶tigt, wenn wir auf einen echten server deployen
# --> ich kommentiere das Ganze mal aus - vllt brauchen wir es irgendwann... vllt auch nicht
# -Goran

#name: Deploy to Server

#on:
#  workflow_run:
#    workflows: ['Build & Push to GHCR']
#    types:
#      - completed

#permissions:
#  contents: read
#  packages: write  # set write permissions ('cause of the organization-fails)

#jobs:
#  deploy:
#    runs-on: ubuntu-latest

#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4

#      - name: Deploy via SSH
#        uses: appleboy/ssh-action@v0.1.9
#        with:
#          host: ${{ secrets.SERVER_HOST }}
#          username: ${{ secrets.SERVER_USER }}
#          key: ${{ secrets.SERVER_SSH_KEY }}
#          port: ${{ secrets.SERVER_PORT }} # optional, default 22
#          script: |
#            cd /app
#            docker compose pull
#            docker compose up -d
