# Git Hub Container Registry
name: Build & Push to GHCR

on:
  push:
    branches: ["main"]
  workflow_run:
    workflows: [ "Run Python Tests (SSMA)" ]
    types:
      - completed

  workflow_dispatch:

permissions:
  contents: read
  packages: write # set write permissions ('cause of the organization-fails)

jobs:
  backend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Convert owner to lowercase
        id: owner_lower
        run: echo "owner_lc=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT


      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.owner_lower.outputs.owner_lc }}/ssma-backend:latest
            ghcr.io/${{ steps.owner_lower.outputs.owner_lc }}/ssma-backend:${{ github.sha }}

  frontend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    needs: backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Convert owner to lowercase
        id: owner_lower
        run: echo "owner_lc=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.owner_lower.outputs.owner_lc }}/ssma-frontend:latest
            ghcr.io/${{ steps.owner_lower.outputs.owner_lc }}/ssma-frontend:${{ github.sha }}
            
  
  image-resizer:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    needs: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert owner to lowercase
        id: owner_lower
        run: |
          echo "owner_lc=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Image Resizer
        uses: docker/build-push-action@v5
        with:
          context: .
          file: image_resizer/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.owner_lower.outputs.owner_lc }}/ssma-image-resizer:latest
            ghcr.io/${{ steps.owner_lower.outputs.owner_lc }}/ssma-image-resizer:${{ github.sha }}
